language: go
go_import_path: github.com/src-d/metdata-retrieval
go:
  - 1.13.x

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

stages:
  - name: tests

os:
  - linux
  - osx

jobs:
  include:
    - stage: tests
      name: 'Unit Tests'
      script:
        - make test-coverage codecov
