language: go
go_import_path: github.com/src-d/metdata-retrieval
go:
  - 1.13.x

stages:
  - name: tests

jobs:
  include:
    - stage: tests
      name: 'Unit Tests'
      script:
        - make test-coverage codecov
