language: go
go_import_path: github.com/src-d/metdata-retrieval
go:
  - 1.13.x

env:
  global:
    - PSQL_USER=user
    - PSQL_PWD=password
    - PSQL_DB=ghsync

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - stage: test
      name: "Integration tests"
      os: linux
      services: docker
      script:
        # only linux supports docker https://docs.travis-ci.com/user/docker/ => tests with docker skipped programmatically ~ OS
        - docker-compose up -d
        - make test-coverage codecov
    - stage: test
      name: "Integration tests"
      os: osx
      script:
        - make test-coverage
    #- stage: test
    #  name: "Integration tests"
    #  os: windows
    #  script:
    #    - run-integration-tests.bat
    # https://docs.travis-ci.com/user/best-practices-security#steps-travis-ci-takes-to-secure-your-data
    # Remove because: The beta Windows support does not obfuscate secure environment variables leaked 
    # into the build log. Please keep reading the next section, on how to avoid leaking secrets to build 
    # logs